//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleAppApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleAppApi.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The camera information provided is not valid..
        /// </summary>
        public static string Camera_InvalidCameraViewInformation {
            get {
                return ResourceManager.GetString("Camera_InvalidCameraViewInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Channel Guid.
        /// </summary>
        public static string Camera_InvalidChannelGuid {
            get {
                return ResourceManager.GetString("Camera_InvalidChannelGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site information is not valid..
        /// </summary>
        public static string Camera_InvalidsiteId {
            get {
                return ResourceManager.GetString("Camera_InvalidsiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue updating camera information. Please try again later..
        /// </summary>
        public static string Camera_InvalidUpdate {
            get {
                return ResourceManager.GetString("Camera_InvalidUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no camera information in system..
        /// </summary>
        public static string Camera_NoMapInformation {
            get {
                return ResourceManager.GetString("Camera_NoMapInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart request data is not valid..
        /// </summary>
        public static string Chart_InvalidRequest {
            get {
                return ResourceManager.GetString("Chart_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no chart data in system..
        /// </summary>
        public static string Chart_NoChartData {
            get {
                return ResourceManager.GetString("Chart_NoChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The execution of the widget operation failed..
        /// </summary>
        public static string Dashboard_FailedExecution {
            get {
                return ResourceManager.GetString("Dashboard_FailedExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dashboard data provided is empty..
        /// </summary>
        public static string Dashboard_InvalidData {
            get {
                return ResourceManager.GetString("Dashboard_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The widget Guid is not valid..
        /// </summary>
        public static string Dashboard_InvalidGuid {
            get {
                return ResourceManager.GetString("Dashboard_InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no dashboard data in database against siteId..
        /// </summary>
        public static string Dashboard_NoDetails {
            get {
                return ResourceManager.GetString("Dashboard_NoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events in the system..
        /// </summary>
        public static string Event_NoData {
            get {
                return ResourceManager.GetString("Event_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string INVALID {
            get {
                return ResourceManager.GetString("INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect..
        /// </summary>
        public static string Login_InCorrectUserNamePassword {
            get {
                return ResourceManager.GetString("Login_InCorrectUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Login model is null..
        /// </summary>
        public static string Login_NullModel {
            get {
                return ResourceManager.GetString("Login_NullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string Login_RequiredPassword {
            get {
                return ResourceManager.GetString("Login_RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field is required..
        /// </summary>
        public static string Login_RequiredUserName {
            get {
                return ResourceManager.GetString("Login_RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is valid:.
        /// </summary>
        public static string Login_ValidUserName {
            get {
                return ResourceManager.GetString("Login_ValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The floor map information is empty..
        /// </summary>
        public static string Map_EmptyFloorMap {
            get {
                return ResourceManager.GetString("Map_EmptyFloorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue updating the list of buildings..
        /// </summary>
        public static string Map_InvalidBuildingUpdate {
            get {
                return ResourceManager.GetString("Map_InvalidBuildingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image of type .jpg,.gif and .png..
        /// </summary>
        public static string Map_InvalidImageExtension {
            get {
                return ResourceManager.GetString("Map_InvalidImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site or Building information provided has invalid number of buildings..
        /// </summary>
        public static string Map_InvalidNumberOfBuilding {
            get {
                return ResourceManager.GetString("Map_InvalidNumberOfBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site or Building information provided has invalid number of floors..
        /// </summary>
        public static string Map_InvalidNumberOfFloors {
            get {
                return ResourceManager.GetString("Map_InvalidNumberOfFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site or Building information provided is not valid..
        /// </summary>
        public static string Map_InvalidSiteBuildingInformation {
            get {
                return ResourceManager.GetString("Map_InvalidSiteBuildingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site or type information is not valid..
        /// </summary>
        public static string Map_InvalidSiteType {
            get {
                return ResourceManager.GetString("Map_InvalidSiteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a file upto 5 mb..
        /// </summary>
        public static string Map_InvalidSize {
            get {
                return ResourceManager.GetString("Map_InvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue updating floor map in system. Please try again later..
        /// </summary>
        public static string Map_IssueUpdatingFloor {
            get {
                return ResourceManager.GetString("Map_IssueUpdatingFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no building information in the system..
        /// </summary>
        public static string Map_NoBuildingInformation {
            get {
                return ResourceManager.GetString("Map_NoBuildingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no map information in system..
        /// </summary>
        public static string Map_NoMapInformation {
            get {
                return ResourceManager.GetString("Map_NoMapInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a valid image..
        /// </summary>
        public static string Map_NoValidImage {
            get {
                return ResourceManager.GetString("Map_NoValidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mmodel ID Bacnet Gateway.
        /// </summary>
        public static string MODEL_ID_BACNET_GATEWAY {
            get {
                return ResourceManager.GetString("MODEL_ID_BACNET_GATEWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery OK,22|Battery low,23|Battery flat,24|Lockset offline,25|Lockset online,26|Door is locked,30|Door is unlocked, 31|FC not matching. Access denied,32|PIN not matching. Access denied,33|PIN timed out. Access denied,34|Card number not found. Access denied,36|Temp card usage exceeded. Access denied,37|Card not active. Access denied,38|Card expired. Access denied,39|Schedule not matching. Access denied,40|High security right not set. Access denied,41|Anti passback. Access denied,42|Anti PB list full. Acces [rest of string was truncated]&quot;;.
        /// </summary>
        public static string S_ASSA_ALL_EVENT_TYPES {
            get {
                return ResourceManager.GetString("S_ASSA_ALL_EVENT_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is granted,2|Access is denied,1|Forced entry alarm,4|Unknown card format,6|Forced entry alarm restored,17|Door held open alarm,9|Door held open alarm restored,19|Door held open warning,10|Door held open warning restored,19|Door not open,3|Request to Exit,5|Input is active,11|Input is normal,55|Unlock mode is on,13|Unlock mode is off,14|High security is on,15|High security is off,16|Tamper detected,20|Tamper restored,21.
        /// </summary>
        public static string S_CAS_ALL_EVENT_TYPES {
            get {
                return ResourceManager.GetString("S_CAS_ALL_EVENT_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel offline,249|Panel connected,250.
        /// </summary>
        public static string S_CONFIG_ALERT_EVENT_TYPES {
            get {
                return ResourceManager.GetString("S_CONFIG_ALERT_EVENT_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is active,100|Input is normal,109|Call started,101|Call finished,102|Call is connected,103|Access is granted (lobby),104|Access is denied (lobby),105|Unlock mode is turned on (lobby),107|Unlock mode is turned off (lobby),108|Dial code not found,120|Call and access schedule inactive,121|Line not connected,122|Line is in use,123|Guard phone connected,125|Calling guard phone,126|Disconnecting call,128|Keyless code schedule is inactive,130|Keyless code not found,131|Main and Aux door are open,132|main doo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string S_TAS_ALL_EVENT_TYPES {
            get {
                return ResourceManager.GetString("S_TAS_ALL_EVENT_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name should be unique in site list..
        /// </summary>
        public static string Site_DuplicateSitesIssue {
            get {
                return ResourceManager.GetString("Site_DuplicateSitesIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an internal issue updating the sites..
        /// </summary>
        public static string Site_InternalIssue {
            get {
                return ResourceManager.GetString("Site_InternalIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site id should be greater than 0..
        /// </summary>
        public static string Site_InvalidSiteId {
            get {
                return ResourceManager.GetString("Site_InvalidSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue retrieving the site/sites..
        /// </summary>
        public static string Site_IssueDatabaseSites {
            get {
                return ResourceManager.GetString("Site_IssueDatabaseSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an issue retrieving the list of templates..
        /// </summary>
        public static string Site_IssueDatabaseTemplates {
            get {
                return ResourceManager.GetString("Site_IssueDatabaseTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue uploading the site on server..
        /// </summary>
        public static string Site_IssueUpload {
            get {
                return ResourceManager.GetString("Site_IssueUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a file upto 5 mb..
        /// </summary>
        public static string Site_LargeFile {
            get {
                return ResourceManager.GetString("Site_LargeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sites in the system..
        /// </summary>
        public static string Site_NoDataSites {
            get {
                return ResourceManager.GetString("Site_NoDataSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no sites in the user request..
        /// </summary>
        public static string Site_NoDataSitesRequest {
            get {
                return ResourceManager.GetString("Site_NoDataSitesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no templates in the system..
        /// </summary>
        public static string Site_NoDataTemplates {
            get {
                return ResourceManager.GetString("Site_NoDataTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site list is successfully updated..
        /// </summary>
        public static string Site_SuccessfulUpdate {
            get {
                return ResourceManager.GetString("Site_SuccessfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is successfully uploaded in server..
        /// </summary>
        public static string Site_SuccessUpload {
            get {
                return ResourceManager.GetString("Site_SuccessUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload valid base64 encoded string..
        /// </summary>
        public static string Site_ValidBase64EncodedData {
            get {
                return ResourceManager.GetString("Site_ValidBase64EncodedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site or Building information provided is not valid..
        /// </summary>
        public static string Status_InvalidSiteBuildingId {
            get {
                return ResourceManager.GetString("Status_InvalidSiteBuildingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Site and Map information is not valid..
        /// </summary>
        public static string Status_InvalidSiteMapGuid {
            get {
                return ResourceManager.GetString("Status_InvalidSiteMapGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no information in system against Site Id and Building Id..
        /// </summary>
        public static string Status_NoData {
            get {
                return ResourceManager.GetString("Status_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no status information in system..
        /// </summary>
        public static string Status_NoStatusInformation {
            get {
                return ResourceManager.GetString("Status_NoStatusInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no system details in database against siteId..
        /// </summary>
        public static string System_NoDetails {
            get {
                return ResourceManager.GetString("System_NoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no panel details in database against panelGuid..
        /// </summary>
        public static string System_NoPanelDetails {
            get {
                return ResourceManager.GetString("System_NoPanelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 1000 LCD4.
        /// </summary>
        public static string TX3_1000_LCD4 {
            get {
                return ResourceManager.GetString("TX3_1000_LCD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 1000 LCD8.
        /// </summary>
        public static string TX3_1000_LCD8 {
            get {
                return ResourceManager.GetString("TX3_1000_LCD8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 200 LCD4.
        /// </summary>
        public static string TX3_200_LCD4 {
            get {
                return ResourceManager.GetString("TX3_200_LCD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 200 LCD8.
        /// </summary>
        public static string TX3_200_LCD8 {
            get {
                return ResourceManager.GetString("TX3_200_LCD8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 2000 LCD4.
        /// </summary>
        public static string TX3_2000_LCD4 {
            get {
                return ResourceManager.GetString("TX3_2000_LCD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 2000 LCD8.
        /// </summary>
        public static string TX3_2000_LCD8 {
            get {
                return ResourceManager.GetString("TX3_2000_LCD8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 Assa.
        /// </summary>
        public static string TX3_ASSA {
            get {
                return ResourceManager.GetString("TX3_ASSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 CX 1 Door.
        /// </summary>
        public static string TX3_CX_1DOOR {
            get {
                return ResourceManager.GetString("TX3_CX_1DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 CX 2 Door.
        /// </summary>
        public static string TX3_CX_2DOOR {
            get {
                return ResourceManager.GetString("TX3_CX_2DOOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 Elevator.
        /// </summary>
        public static string TX3_ELEVATOR {
            get {
                return ResourceManager.GetString("TX3_ELEVATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 EMER 1S.
        /// </summary>
        public static string TX3_EMER_1S {
            get {
                return ResourceManager.GetString("TX3_EMER_1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 EMER 200KS.
        /// </summary>
        public static string TX3_EMER_200KS {
            get {
                return ResourceManager.GetString("TX3_EMER_200KS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 Nano.
        /// </summary>
        public static string TX3_NANO {
            get {
                return ResourceManager.GetString("TX3_NANO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 System.
        /// </summary>
        public static string TX3_SYSTEM {
            get {
                return ResourceManager.GetString("TX3_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX3 Touch.
        /// </summary>
        public static string TX3_TOUCH {
            get {
                return ResourceManager.GetString("TX3_TOUCH", resourceCulture);
            }
        }
    }
}
